version: "3"

services:
  user-db:
    image: mysql:latest
    container_name: user-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_db
    volumes:
      - user-db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  material-db:
    image: mysql:latest
    container_name: material-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: material_db
    volumes:
      - material-db-data:/var/lib/mysql
    ports:
      - "3307:3306"

  transaction-db:
    image: mysql:latest
    container_name: transaction-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: transaction_db
    volumes:
      - transaction-db-data:/var/lib/mysql
    ports:
      - "3308:3306"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    depends_on:
      - rabbitmq
      - user-db
    environment:
      - APP_PORT=3000
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DB_HOST=user-db
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=user_db
    ports:
      - "3000:3000"

  material-service:
    build:
      context: ./material-service
      dockerfile: Dockerfile
    container_name: material-service
    depends_on:
      - rabbitmq
      - material-db
    environment:
      - APP_PORT=3001
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DB_HOST=material-db
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=material_db
    ports:
      - "3001:3001"

  transaction-service:
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    container_name: transaction-service
    depends_on:
      - rabbitmq
      - transaction-db
    environment:
      - APP_PORT=3002
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DB_HOST=transaction-db
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=transaction_db
    ports:
      - "3002:3002"

volumes:
  user-db-data:
  material-db-data:
  transaction-db-data:
